### ISSUE TITLE
build of contracts fails behind proxy

### ISSUE THREAD

**Issue by thorstenhirsch** [ethereum-oasis/baseline#86] opened 2020-04-01 15:37 UTC
## Expected Behavior
build respects http_proxy environment variable

## Actual Behavior
build ignores http_proxy variable (to be more specific: node-fetch ignores the variable)

```
> radish-34@1.0.0 build:contracts /home/digits/src/baseline/radish34
> pushd contracts && npm run build && popd

~/src/baseline/radish34/contracts ~/src/baseline/radish34

> contracts@1.0.0 build /home/digits/src/baseline/radish34/contracts
> sol-compiler

{ FetchError: request to https://ethereum.github.io/solc-bin/bin/list.json failed, reason: connect ETIMEDOUT 185.199.111.153:443
    at ClientRequest.<anonymous> (/home/digits/src/baseline/radish34/contracts/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'FetchError',
  message: 'request to https://ethereum.github.io/solc-bin/bin/list.json failed, reason: connect ETIMEDOUT 185.199.111.153:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contracts@1.0.0 build: `sol-compiler`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contracts@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/digits/.npm/_logs/2020-04-01T15_13_49_337Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! radish-34@1.0.0 build:contracts: `pushd contracts && npm run build && popd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the radish-34@1.0.0 build:contracts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/digits/.npm/_logs/2020-04-01T15_13_49_349Z-debug.log
make: *** [Makefile:23: contracts] Error 1
```
There's an issue for node-fetch to respect the env variable, but in one of the answers it says, that node-fetch is the wrong abstraction level for that. So it seems when you're using node-fetch you have to implement the proxy settings in JS yourself.

A better solution is probably to download the contracts in sol-compiler in a different way than using the node-fetch, e.g. curl does quite a good job, is widely available, and respects the http_proxy env variable.

## Steps to Reproduce the Problem

  1. export http_proxy=...; export https_proxy=$http_proxy
  1. make

## Specifications

  - Version: master branch (2020/03/31)
  - Platform: Linux/x64
  - Subsystem: RHEL7

**Comment by skarred14** [comment] 2020-04-01 17:14
thanks for bringing this up, above PR addresses this fix @thorstenhirsch

**Comment by skarred14** [comment] 2020-04-03 19:55
@thorstenhirsch The issue must be due to the setting to fetch a compiler version if there is no local one found. In `contracts/package.json`, could you add something like this for the build script: 
`git config --global url.ssh://git@github.com/.insteadOf https://github.com/ && npm run build`. We are looking into cleaning up contracts/ and deploy/ and making it a single service for all contract mgmt in radish34 and can address this issue there

**Comment by thorstenhirsch** [comment] 2020-04-06 11:32
Hi @skarred14, I'm not sure what your goal is with the changes in the gitconfig, because using ssh instead of https makes things worse for me. My only way to fetch a repo behind a http(s) proxy is to use the http(s) proxy. There's no way to fetch repos from the internet with ssh.

But I tried it anyhow. Result:
```
> pushd contracts && npm run build && popd

~/src/baseline/radish34/contracts ~/src/baseline/radish34

> contracts@1.0.0 build /home/digits/src/baseline/radish34/contracts
> sol-compiler

Compiling 21 contracts (BN256G2.sol,ERC165.sol,ERC165Compatible.sol,ERC1820ImplementerInterface.sol,ERC1820Registry.sol,ERC20.sol,ERC20Interface.sol,IERC165.sol,IOrgRegistry.sol,IShield.sol,IVerifier.sol,MerkleTree.sol,OrgRegistry.sol,Ownable.sol,Pairing.sol,Registrar.sol,Roles.sol,SafeMath.sol,SampleERC1820Implementer.sol,Shield.sol,Verifier.sol) with Solidity v0.5.8...
Downloading soljson-v0.5.8+commit.23d335f2.js...
{ FetchError: request to https://ethereum.github.io/solc-bin/bin/soljson-v0.5.8+commit.23d335f2.js failed, reason: connect EHOSTUNREACH 185.199.111.153:443
    at ClientRequest.<anonymous> (/home/digits/src/baseline/radish34/contracts/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'FetchError',
  message: 'request to https://ethereum.github.io/solc-bin/bin/soljson-v0.5.8+commit.23d335f2.js failed, reason: connect EHOSTUNREACH 185.199.111.153:443',
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contracts@1.0.0 build: `sol-compiler`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contracts@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/digits/.npm/_logs/2020-04-06T11_23_08_409Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! radish-34@1.0.0 build:contracts: `pushd contracts && npm run build && popd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the radish-34@1.0.0 build:contracts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/digits/.npm/_logs/2020-04-06T11_23_08_420Z-debug.log
make: *** [Makefile:23: contracts] Error 1
```
Didn't work. But the repo is hosted on ethereum.github.io (not github.com), so the git config command you're up to is probably:
`git config --global url.ssh://git@ethereum.github.io/.insteadOf https://ethereum.github.io/`
However, it doesn't make any difference at all. The error remains exactly the same. That's because "git clone" isn't used, but node-fetch is still being used for the download. And node-fetch doesn't respect the git config, that's why it still uses https.

**Comment by skarred14** [comment] 2020-04-06 15:05
thanks @thorstenhirsch, i assumed the issue you were facing is during the build process when the dependency was trying to connect to github. looking into this shortly, will get back and post an update here

**Comment by skarred14** [comment] 2020-04-06 20:01
https://github.com/ethereum-oasis/baseline/tree/fix-contracts-offline-compilation

@thorstenhirsch could you try this and let me know if this solves your issue?

**Comment by thorstenhirsch** [comment] 2020-04-06 20:52
@skarred14 just tried it, but node-fetch is still being called, still doesn't respect my proxy settings, so it still runs on error.
```
> pushd contracts && npm run build && popd

~/src/baseline/radish34/contracts ~/src/baseline/radish34

> contracts@1.0.0 build /home/digits/src/baseline/radish34/contracts
> sol-compiler

{ FetchError: request to https://ethereum.github.io/solc-bin/bin/list.json failed, reason: connect ETIMEDOUT 185.199.111.153:443
    at ClientRequest.<anonymous> (/home/digits/src/baseline/radish34/contracts/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'FetchError',
  message: 'request to https://ethereum.github.io/solc-bin/bin/list.json failed, reason: connect ETIMEDOUT 185.199.111.153:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contracts@1.0.0 build: `sol-compiler`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contracts@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/digits/.npm/_logs/2020-04-06T20_44_59_900Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! radish-34@1.0.0 build:contracts: `pushd contracts && npm run build && popd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the radish-34@1.0.0 build:contracts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/digits/.npm/_logs/2020-04-06T20_44_59_912Z-debug.log
make: *** [Makefile:23: contracts] Error 1

```

**Comment by thorstenhirsch** [comment] 2020-04-06 21:20
I think the root cause of the problem is https://github.com/0xProject/0x-monorepo/pull/1596, in which they changed from a static list of solidity releases to dynamically fetching it with this line:
```
src/utils/compiler.ts:        const versionList = await fetch('https://ethereum.github.io/solc-bin/bin/list.json');
```
That's where the node-fetch call in the error message stems from.

**Comment by skarred14** [comment] 2020-04-06 23:34
that makes sense, and thanks for posting this on 0xProject repo. After some more diagnosis I am inclined 

I see the potential root cause is: `let solcJSReleasesCache: BinaryPaths | undefined;`, similar to what you have pointed out. An alternative until this is fixed upstream, could be to manually run individual compilable artifacts importing the compiler and running a custom script. There is a larger effort to optimize for a better contract management system #19 and #71 , where we will account for this aspect.

**Comment by breakpointer** [comment] 2020-05-07 13:35
Since there's not been much activity on this in a while I'm going to close it now.

**Closed by breakpointer** 2020-05-07 13:35 UTC
Labels: :beetle: bug
